name: Update PIT code

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  #push:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "update"
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update components
        run: |
          ./update_script.sh
          
      - name: Push to public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        run: |
          git clone https://khufkens:$GITHUB_TOKEN@github.com/bluegreen-labs/phenocam_installation_tool_v2
          
          cd phenocam_installation_tool_v2
          git config --unset-all http.https://github.com/.extraheader
          
          git config user.name "khufkens"
          git config user.email "koen.hufkens@gmail.com"
          
          mv ../PIT.sh .
          mv ../README.md .
          
          git add PIT.sh
          git commit -m "update PIT"
          
          git push
